from django.core.management.base import BaseCommand
from properties.models import Property, PropertyImage, Landmark
from leads.models import Lead, Agent
from blogs.models import BlogPost
from users.models import Customer, PropertyBought, InterestedProperty, PaymentHistory
from datetime import date

class Command(BaseCommand):
    help = 'Load all frontend data into backend database'

    def handle(self, *args, **kwargs):
        self.stdout.write('Loading all frontend data...')
        
        # Clear existing data
        Property.objects.all().delete()
        Lead.objects.all().delete()
        Agent.objects.all().delete()
        BlogPost.objects.all().delete()
        Customer.objects.all().delete()
        
        # Properties data
        properties_data = [
            {'title': 'Premium Residential Plot in Hirapur', 'description': 'East facing residential plot in a prime locality of Hirapur. Perfect for building your dream home. Walking distance from Park Market.', 'price': 35, 'location': 'Hirapur', 'type': 'Plot', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 2178, 'dimensions': '33 x 66 ft', 'facing': 'East', 'amenities': ['East Facing', 'Boundary Wall', 'Water Connection', 'Electricity'], 'featured': True, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Park Market', 'distance': '0.5 km', 'category': 'Lifestyle'}, {'name': 'Carmel School', 'distance': '1.2 km', 'category': 'Education'}, {'name': 'Dhanbad Railway Station', 'distance': '3.5 km', 'category': 'Transport'}, {'name': 'Hirapur Durga Mandir', 'distance': '0.8 km', 'category': 'Religious'}]},
            {'title': 'Luxury 4BHK Villa in Saraidhela', 'description': 'Independent luxury villa with private garden and terrace. Located in the posh area of Saraidhela near Big Bazaar.', 'price': 125, 'location': 'Saraidhela', 'type': 'Villa', 'status': 'Ready to Move', 'listing_type': 'Buy', 'bedrooms': 4, 'bathrooms': 4, 'area': 3200, 'facing': 'North-East', 'amenities': ['Private Garden', 'Gated Community', 'Modular Kitchen', 'Servant Quarter', '24/7 Security'], 'featured': True, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Commercial Plot at Bank More', 'description': 'High-value commercial land suitable for shopping complex or office building. Main road frontage.', 'price': 250, 'location': 'Bank More', 'type': 'Plot', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 4500, 'dimensions': '50 x 90 ft', 'facing': 'North', 'amenities': ['Main Road Facing', 'Corner Plot', 'Electricity', 'Water Connection'], 'featured': True, 'new_launch': False, 'prime_commercial': True, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'City Centre', 'distance': '0.2 km', 'category': 'Lifestyle'}, {'name': 'Railway Station', 'distance': '1.5 km', 'category': 'Transport'}, {'name': 'Bank of India HQ', 'distance': '0.1 km', 'category': 'Business'}]},
            {'title': 'Gated Community Plot near ISM', 'description': 'Secure residential plot within a gated society. Black top roads, street lights, and drainage system already developed.', 'price': 28, 'location': 'Saraidhela', 'type': 'Plot', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 1500, 'dimensions': '30 x 50 ft', 'facing': 'West', 'amenities': ['Gated Community', 'Black Top Road', 'Street Lights', 'Park/Garden'], 'featured': False, 'new_launch': True, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'ISM Dhanbad', 'distance': '0.5 km', 'category': 'Education'}, {'name': 'Big Bazaar', 'distance': '2.0 km', 'category': 'Lifestyle'}, {'name': 'Asian Jalan Hospital', 'distance': '2.5 km', 'category': 'Healthcare'}]},
            {'title': 'Modern Duplex Villa in Kusum Vihar', 'description': 'Newly constructed duplex villa with contemporary architecture. Peaceful neighborhood with elite gentry.', 'price': 85, 'location': 'Kusum Vihar', 'type': 'Villa', 'status': 'Ready to Move', 'listing_type': 'Buy', 'bedrooms': 3, 'bathrooms': 3, 'area': 2400, 'facing': 'South-East', 'amenities': ['Terrace Garden', 'Car Parking', 'Vastu Compliant', 'Water Supply'], 'featured': True, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1600596542815-22b8c153bd30?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Farmhouse Land in Govindpur', 'description': 'Expansive land parcel ideal for farmhouse or weekend getaway. Lush greenery and boundary wall done.', 'price': 45, 'location': 'Govindpur', 'type': 'Farmhouse', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 10000, 'dimensions': '100 x 100 ft', 'facing': 'East', 'amenities': ['Boundary Wall', 'Electricity', 'Water Connection', 'Greenery'], 'featured': False, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Corner Plot in Dhansar', 'description': 'Two-side open corner plot in Dhansar. Ideal for residential cum commercial use.', 'price': 42, 'location': 'Dhansar', 'type': 'Plot', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 1800, 'dimensions': '40 x 45 ft', 'facing': 'North-West', 'amenities': ['Corner Plot', 'Road Connectivity', 'Drainage System'], 'featured': False, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Dhansar Thana', 'distance': '0.3 km', 'category': 'Business'}, {'name': 'Bank More', 'distance': '1.2 km', 'category': 'Lifestyle'}, {'name': 'Patliputra Medical College', 'distance': '4.0 km', 'category': 'Healthcare'}]},
            {'title': 'Shree Vihar Phase 2 - Plots', 'description': 'New launch of residential plots in Shree Vihar township. Booking open at pre-launch prices.', 'price': 18, 'location': 'Govindpur', 'type': 'Plot', 'status': 'Under Construction', 'listing_type': 'Buy', 'area': 1200, 'dimensions': '30 x 40 ft', 'facing': 'Varied', 'amenities': ['Gated Community', 'Club House', 'Temple', 'Park'], 'featured': False, 'new_launch': True, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1628744876497-eb30460be9f6?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Delhi Public School', 'distance': '2.0 km', 'category': 'Education'}, {'name': 'GT Road Highway', 'distance': '0.5 km', 'category': 'Transport'}, {'name': 'Local Market', 'distance': '0.8 km', 'category': 'Lifestyle'}]},
            {'title': 'Premium Villa Project', 'description': 'Upcoming luxury villa project in Koyla Nagar with world-class amenities.', 'price': 150, 'location': 'Koyla Nagar', 'type': 'Villa', 'status': 'Under Construction', 'listing_type': 'Buy', 'bedrooms': 5, 'bathrooms': 5, 'area': 4000, 'amenities': ['Swimming Pool', 'Gymnasium', 'Home Theater', 'Smart Home'], 'featured': True, 'new_launch': True, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Commercial Complex Land', 'description': 'Prime land for commercial complex near Steel Gate market.', 'price': 180, 'location': 'Steel Gate', 'type': 'Commercial', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 3000, 'dimensions': '50 x 60 ft', 'facing': 'Main Road', 'amenities': ['Main Road Facing', 'High Footfall'], 'featured': False, 'new_launch': False, 'prime_commercial': True, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Budget Residential Plot', 'description': 'Affordable plot for investment in Wasseypur area. Developing zone.', 'price': 12, 'location': 'Wasseypur', 'type': 'Plot', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 1000, 'dimensions': '25 x 40 ft', 'facing': 'South', 'amenities': ['Electricity', 'Water Connection'], 'featured': False, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Wasseypur Market', 'distance': '0.5 km', 'category': 'Lifestyle'}, {'name': 'Dhanbad Station', 'distance': '2.5 km', 'category': 'Transport'}]},
            {'title': 'Fully Furnished Villa for Rent', 'description': 'Company lease preferred. 4BHK fully furnished villa in elite colony.', 'price': 45, 'location': 'Koyla Nagar', 'type': 'Villa', 'status': 'Ready to Move', 'listing_type': 'Rent', 'bedrooms': 4, 'bathrooms': 3, 'area': 2800, 'amenities': ['Furniture', 'AC', 'Power Backup', 'Garage'], 'featured': False, 'new_launch': False, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Green Valley Township', 'description': 'Upcoming eco-friendly township on Tundi Road. Pre-launch booking open for residential plots with wide roads and drainage.', 'price': 15, 'location': 'Tundi Road', 'type': 'Plot', 'status': 'Under Construction', 'listing_type': 'Buy', 'area': 1500, 'dimensions': '30 x 50 ft', 'facing': 'East/West', 'amenities': ['Park', 'Jogging Track', 'Street Lights', 'Security'], 'featured': True, 'new_launch': True, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Birsa Munda Park', 'distance': '5.0 km', 'category': 'Lifestyle'}, {'name': 'Govindpur Highway', 'distance': '3.0 km', 'category': 'Transport'}]},
            {'title': 'Industrial Land on GT Road', 'description': 'Large parcel of land suitable for warehousing, factory, or logistics hub. Direct highway access.', 'price': 350, 'location': 'Govindpur', 'type': 'Commercial', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 15000, 'dimensions': '100 x 150 ft', 'facing': 'Highway', 'amenities': ['Highway Access', 'Industrial Zone', 'Electricity', 'Water'], 'featured': False, 'new_launch': False, 'prime_commercial': True, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&w=800&q=80']},
            {'title': 'Sunrise Enclave Phase 1', 'description': 'Gated community plots near Memco More. Development in full swing. Ideal for investment.', 'price': 22, 'location': 'Bartand', 'type': 'Plot', 'status': 'Under Construction', 'listing_type': 'Buy', 'area': 1800, 'dimensions': '36 x 50 ft', 'facing': 'North', 'amenities': ['Gated Community', 'Drainage', 'Water Supply'], 'featured': False, 'new_launch': True, 'prime_commercial': False, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'], 'landmarks': [{'name': 'Memco More', 'distance': '0.5 km', 'category': 'Transport'}, {'name': 'Big Bazaar', 'distance': '3.0 km', 'category': 'Lifestyle'}, {'name': 'Dhanbad Public School', 'distance': '1.5 km', 'category': 'Education'}]},
            {'title': 'Market Complex Land', 'description': 'Corner plot in the heart of Jharia market. High footfall area suitable for shopping complex.', 'price': 120, 'location': 'Jharia', 'type': 'Commercial', 'status': 'Ready to Move', 'listing_type': 'Buy', 'area': 2500, 'dimensions': '50 x 50 ft', 'facing': 'Corner', 'amenities': ['Market Area', 'Corner Plot', 'High Visibility'], 'featured': True, 'new_launch': False, 'prime_commercial': True, 'agent_contact': '+91 9876543210', 'images': ['https://images.unsplash.com/photo-1519999482648-25049ddd37b1?auto=format&fit=crop&w=800&q=80']},
        ]
        
        for prop_data in properties_data:
            landmarks = prop_data.pop('landmarks', [])
            images = prop_data.pop('images', [])
            prop = Property.objects.create(**prop_data)
            for idx, img in enumerate(images):
                PropertyImage.objects.create(property=prop, image_url=img, order=idx)
            for lm in landmarks:
                Landmark.objects.create(property=prop, **lm)
        
        # Leads
        Lead.objects.bulk_create([
            Lead(name='Amit Kumar', email='amit@example.com', phone='+91 9876543210', source='Website', status='New'),
            Lead(name='Sneha Roy', email='sneha@example.com', phone='+91 9876543211', source='Facebook', status='Contacted'),
            Lead(name='Rajiv Singh', email='rajiv@example.com', phone='+91 9876543212', source='Referral', status='Closed'),
            Lead(name='Pooja Verma', email='pooja@example.com', phone='+91 9876543213', source='Website', status='New'),
        ])
        
        # Agents
        Agent.objects.bulk_create([
            Agent(name='Rahul Sharma', role='Senior Consultant', phone='+91 9876500001', email='rahul@shreeshyamcity.com', deals=45, photo='https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=100&q=80'),
            Agent(name='Priya Singh', role='Sales Head', phone='+91 9876500002', email='priya@shreeshyamcity.com', deals=32, photo='https://images.unsplash.com/photo-1573496359-936d9dd3a94b?auto=format&fit=crop&w=100&q=80'),
        ])
        
        # Blogs
        BlogPost.objects.bulk_create([
            BlogPost(title='Why Land Investment is the Best in Dhanbad', excerpt='Understanding the appreciation rates of plots vs flats in the current market scenario.', content='Land has always been a goldmine in Dhanbad...', date=date(2023, 11, 1), author='Rahul Sharma', image_url='https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80'),
            BlogPost(title='Guide to Buying Vastu Compliant Plots', excerpt='Key vastu tips to check before purchasing a residential plot for your home.', content='Orientation, slope, and shape of the plot matter significantly...', date=date(2023, 10, 25), author='Amit Verma', image_url='https://images.unsplash.com/photo-1599809275372-b7f5d7ebac64?auto=format&fit=crop&w=600&q=80'),
        ])
        
        # Customers
        cust = Customer.objects.create(name='Rajesh Kumar', email='rajesh.kumar@example.com', phone='+91 98765 43210', address='123, Green Park, Dhanbad', status='VIP', avatar_url='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80', total_paid=4500000, pending_amount=500000, notes='Interested in commercial properties near Bank More.')
        PropertyBought.objects.create(customer=cust, property_id='p1', title='Luxury Villa in Hirapur', price=4500000, date=date(2023, 5, 15))
        InterestedProperty.objects.create(customer=cust, property_id='p3', title='Commercial Shop in Bank More', status='Offer Made')
        PaymentHistory.objects.bulk_create([
            PaymentHistory(customer=cust, amount=100000, date=date(2023, 1, 10), description='Booking Amount', status='Paid'),
            PaymentHistory(customer=cust, amount=2000000, date=date(2023, 3, 15), description='First Installment', status='Paid'),
            PaymentHistory(customer=cust, amount=2400000, date=date(2023, 5, 15), description='Final Payment', status='Paid'),
        ])
        
        self.stdout.write(self.style.SUCCESS(f'Successfully loaded {Property.objects.count()} properties, {Lead.objects.count()} leads, {Agent.objects.count()} agents, {BlogPost.objects.count()} blogs, and {Customer.objects.count()} customers!'))
