# Generated by Django 4.2.7 on 2026-02-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_agent'),
        ('users', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='leads.agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent')], default='admin', max_length=10),
        ),
    ]
