# Generated by Django 4.2.7 on 2026-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='arnavkaraj@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default='9414454858', max_length=20),
            preserve_default=False,
        ),
    ]
