# Generated by Django 4.2.7 on 2026-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_agent_options_enquiry_email_enquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Resolved', 'Resolved')], default='Unread', max_length=10),
        ),
    ]
