# Generated by Django 4.2.7 on 2026-02-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
    ]
