# Generated by Django 4.2.7 on 2026-03-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_agent_email_remove_agent_password_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
