# Generated by Django 4.2.7 on 2026-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('property_trends', 'Property Trends in Dhanbad'), ('government_schemes', 'Government Housing Schemes'), ('area_guides', 'Area Guides')], max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('lifestyle', models.TextField(blank=True, null=True)),
                ('connectivity', models.TextField(blank=True, null=True)),
                ('key_landmarks', models.JSONField(blank=True, null=True)),
                ('avg_price', models.CharField(blank=True, max_length=100, null=True)),
                ('rental_yield', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_to_read', models.CharField(blank=True, max_length=50, null=True)),
                ('writer', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
