# Generated by Django 4.2.7 on 2026-02-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Plot', 'Plot'), ('Villa', 'Villa'), ('Farmhouse', 'Farmhouse'), ('Commercial', 'Commercial'), ('Apartment', 'Apartment')], max_length=20)),
                ('status', models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], max_length=30)),
                ('listing_type', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField()),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('amenities', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('new_launch', models.BooleanField(default=False)),
                ('prime_commercial', models.BooleanField(default=False)),
                ('agent_contact', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Transport', 'Transport'), ('Lifestyle', 'Lifestyle'), ('Religious', 'Religious'), ('Business', 'Business')], max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='properties.property')),
            ],
        ),
    ]
